import React, { useState } from 'react'
import Head from 'next/head'
import { useSession } from 'next-auth/react'

import Button from 'components/Button'
import Input from 'components/Input'
import SpotifyTrack from 'components/SpotifyTrack'

const Home = () => {
  const { data: session } = useSession()
  const [keyword, setKeyword] = useState('')
  const [data, setData] = useState(null)

  const onClick = async () => {
    const result = await fetch(`/api/spotify/search/${keyword}`)
    const json = await result.json()

    if (json.success) {
      setData(json.data.items)
    } else {
      // TODO: handle error
    }
  }

  return (
    <>
      <Head>
        <title>Spotify App for Hivers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? (
        <div>
          <div className="flex gap-4">
            <Input onChange={val => setKeyword(val)} value={keyword} />

            <Button onClick={onClick}>Search</Button>
          </div>

          <div className="mt-8 flex flex-col gap-4">
            {data && data.map(track => <SpotifyTrack key={track.id} track={track} />)}
          </div>
        </div>
      ) : (
        <div>Hi there! Please login to use this app :)</div>
      )}
    </>
  )
}

export default Home
