import React, { useState } from 'react'
import Head from 'next/head'

import Button from 'components/Button'
import Input from 'components/Input'
import AuthButton from 'components/AuthButton'

const Home = () => {
  const [keyword, setKeyword] = useState('')
  const [data, setData] = useState(null)

  console.log('data  is:', data)

  const onClick = async () => {
    const result = await fetch(`/api/spotify/search/${keyword}`)
    const json = await result.json()

    if (json.success) {
      setData(json.data.items)
    } else {
      // TODO: handle error
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthButton />

      <main style={{ padding: '20px' }}>
        <Input onChange={val => setKeyword(val)} value={keyword} />

        <Button onClick={onClick}>Search songs</Button>

        {data &&
          data.map(track => (
            <div
              className="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100"
              key={track.id}
            >
              <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">
                {track.name}
              </h5>
              <p className="font-normal text-gray-700">
                {track.artists.map(artist => artist.name).join(', ')}
              </p>
            </div>
          ))}
      </main>
    </>
  )
}

export default Home
